
MODEL_NAMES_MAPPER = {
    "vcl": "VCL",
    "vcl_random_200": "VCL + Random Coreset",
    "vcl_k-center_200": "VCL + K-Center Coreset",
    "vcl_pca-k-center_200": "VCL + PCA K-Center Coreset",
    "vcl_class_balanced_200": "VCL + Class Balanced Coreset",
    "evcl": "EVCL",
    "evcl_random_200": "EVCL + Random Coreset",
    "evcl_k-center_200": "EVCL + K-Center Coreset",
    "evcl_pca-k-center_200": "EVCL + PCA K-Center Coreset",
    "evcl_class_balanced_200": "EVCL + Class Balanced Coreset",
    "vcl_ewc": "EVCL",
    "vcl_ewc_random_200": "EVCL + Random Coreset",
    "vcl_ewc_k-center_200": "EVCL + K-Center Coreset",
    "vcl_ewc_pca-k-center_200": "EVCL + PCA K-Center Coreset",
    "vcl_ewc_class_balanced_200": "EVCL + Class Balanced Coreset",
    "ewc": "EWC (λ = 100)",
    "coreset_only_random_200": "Random Coreset Only",
    "coreset_only_k-center_200": "K-Center Coreset Only",
    "coreset_only_pca-k-center_200": "PCA K-Center Coreset Only",
    "coreset_only_class_balanced_200": "Class Balanced Coreset Only",
}